 steps:

#loguearse en dockerHub
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']

#compilar la imagen
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/$_REPOSITORY:$_TAG .']
   secretEnv: ['USERNAME']

#copiarla en dockerHub
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/$_REPOSITORY:$_TAG']
   secretEnv: ['USERNAME']
 substitutions:
     _REPOSITORY_1: abcjobs
     _TAG_1: latest
 availableSecrets:
   secretManager:
   - versionName: projects/proyecto1-399312/secrets/dockerhub-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/proyecto1-399312/secrets/dockerhub-username/versions/1
     env: 'USERNAME'
