apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: deploy-abcjobs-web
description: Canalización del FrontEnd Web
serialPipeline:
  stages:
  - targetId: dev-environment
    profiles: [desarrollo]
  - targetId: production-environment
    profiles: [produccion]
    strategy:
      canary:
        runtimeConfig:
          cloudRun:
            automaticTrafficControl: true
        canaryDeployment:
          percentages: [25,50,75]
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-environment
description: Servicio de pruebas en CloudRun
run:
  location: projects/proyecto1-399312/locations/us-central1
  #location: projects/abcjobsfront/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production-environment
description: Servicio de despliegue a producción en CloudRun
run:
  location: projects/proyecto1-399312/locations/us-central1
