 steps:
 - name: 'ubuntu'
   entrypoint: 'bash'
   args: ['-c', 'npm install']
 - name: 'ubuntu'
   entrypoint: 'bash'
   args: ['-c', 'ng build']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
   secretEnv: ['USERNAME', 'PASSWORD']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker build -t $$USERNAME/${REPOSITORY}:${TAG} .']
   secretEnv: ['USERNAME']
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: 'bash'
   args: ['-c', 'docker push $$USERNAME/${REPOSITORY}:${TAG}']
   secretEnv: ['USERNAME']
 substitutions:
     REPOSITORY: abcjobs
     TAG: latest
 availableSecrets:
   secretManager:
   - versionName: projects/abcjobsfront/secrets/dockerhub-password/versions/1
     env: 'PASSWORD'
   - versionName: projects/abcjobsfront/secrets/dockerhub-username/versions/1
     env: 'USERNAME'

