apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-qs-production
spec:
  template:
    spec:
      containers:
      - image: docker.io/cristaor/abcjobs:latest
        name: abcjobsweb
        ports:
        - containerPort: 80
          name: http1
